name: Gerar APK Frama
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Resolve o aviso do Node.js
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle' # Mudamos para Oracle que é mais estável para Android
          java-version: '17'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2' # Versão estável que não dá erro de Kotlin
          channel: 'stable'
          
      - name: Install Dependencies
        run: flutter pub get

      - name: Build APK
        # Adicionamos uma flag para ignorar erros de ícones e focar no código
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Frama-APK
          path: build/app/outputs/flutter-apk/app-release.apk
